apiVersion: v1
kind: Service
metadata:
  name: backstage-service
  namespace: backstage
  labels:
    app: backstage
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: backstage
    version: v1
